# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Android Testsuite

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.eslint*'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.eslint*'

jobs:
  test:
    name: Android ${{ matrix.versions.android }} Test
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      node-version: 20
      default_java-distro: temurin
      default_java-version: 17
      default_system-image-arch: x86_64
      default_system-image-target: google_apis

    strategy:
      matrix:
        versions:
          - android: 7
            android-api: 24
          - android: 7.1
            android-api: 25
          - android: 8
            android-api: 26
          - android: 8.1
            android-api: 27
            system-image-arch: x86
          - android: 9
            android-api: 28
          - android: 10
            android-api: 29
          - android: 11
            android-api: 30
          - android: 12
            android-api: 31
          - android: 12L
            android-api: 32
          - android: 13
            android-api: 33
          - android: 14
            android-api: 34

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.default_java-distro }}
          java-version: ${{ env.default_java-version }}

      - name: Install Android SDK Command-Line Tools
        run: |
          # Create directory for Android SDK
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chown $USER:$USER /usr/local/lib/android/sdk -R

          # Download and install SDK tools
          curl -o sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip sdk-tools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools
          mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Set up Android SDK environment
        run: |
          echo "export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses
        shell: bash

      - name: Install Android Build Tools and System Image
        run: |
          sdkmanager --install 'platform-tools' 'platforms;android-${{ matrix.versions.android-api }}' 'system-images;android-${{ matrix.versions.android-api }};google_apis;x86_64'
          sdkmanager --install 'emulator'
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Create AVD directory
        run: mkdir -p /home/runner/.android/avd

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.versions.android-api }}
          target: ${{ env.system-image-target }}
          arch: ${{ env.system-image-arch }}
          force-avd-creation: true
          disable-animations: false
          emulator-boot-timeout: 1200
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim

      - name: Run paramedic tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.versions.android-api }}
          target: ${{ env.system-image-target }}
          arch: ${{ env.system-image-arch }}
          force-avd-creation: true
          disable-animations: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ${{ env.paramedic }} --config ./pr/local/${{ env.test_config }} --plugin ${{ env.test_plugin_path }}

      - name: Terminate Emulator
        run: adb -s emulator-5554 emu kill
